### ISSUE TITLE
All conda tests fail due to lack of epicsmacrolib availability on conda

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/whatrecord#156]
Is this expected?
https://github.com/pcdshub/whatrecord/actions/runs/4611817009

**Comment by klauer** [comment]
This is expected per https://github.com/pcdshub/whatrecord/pull/152

(epicsmacrolib is unavailable on conda-forge)

**Comment by klauer** [comment]
(This is a valid issue that needs addressing and should be noted in the issues section; reopening)
